title: Tomek
description: Moja strona
baseurl: ""
url: "https://janzbedny.github.io"
theme: jekyll-theme-cayman

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

menu:
  - title: Strona główna
    url: /
  - title: O mnie
    url: /about.md
  - title: Blog
    url: /blog/
