title: Inż Tomasz Kowalczyk
theme: jekyll-theme-cayman
menu:
  - title: Dane osobowe
    url: /
  - title: Wykształcenie
    url: /about.html
  - title: Doświadczenie zawodowe
    url: /experience.html
