title: Tomasz Kowalczyk
theme: jekyll-theme-cayman
include:
  - assets/css

menu:
  - title: Strona główna
    url: /
  - title: Dane osobowe
    url: /personal.html
  - title: Wykształcenie
    url: /about.html
  - title: Doświadczenie zawodowe
    url: /experience.html
  - title: CV
    url: /cv.html

