title: "Moja strona"
description: "Opis mojej strony"
theme: jekyll-theme-cayman

# Sidebar menu items
menu:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about.html"
  - title: "Blog"
    url: "/blog/"

# Dark mode
dark_mode: true

# Markdown
markdown: kramdown
highlighter: rouge

plugins: []
